name: Build Artifact

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  # workflow_dispatch:
  #   inputs:
  #     action:
  #       description: 'Specify action: deploy'
  #       required: true
  #       default: 'deploy'

jobs:
  # Build Job
  build:
    # needs: save-previous-production-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Run Tests
        run: |
          npm test

      - name: Build Project
        run: |
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: dist