name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      working-directory: vite-project
      run: npm install

    - name: Build the project
      working-directory: vite-project
      run: npm run build

    - name: Archive production artifacts
      run: |
        mkdir deploy-package
        cp -r vite-project/dist deploy-package/
        cp vite-project/appspec.yml deploy-package/
        cp -r vite-project/scripts deploy-package/
        cd deploy-package
        zip -r ../deploy-package.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_DEPLOY_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create S3 bucket if it doesn't exist
      run: |
        aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET }} || aws s3api create-bucket --bucket ${{ secrets.S3_BUCKET }} --region ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp deploy-package.zip s3://${{ secrets.S3_BUCKET }}/deploy-package.zip

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ secrets.AWS_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deploy-package.zip
