name: CI/CD for React

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify action: deploy or rollback'
        required: true
        default: 'deploy'

jobs:
  # Save Previous Production File Job
  save-previous-production-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download current production artifact
        id: download_current
        uses: actions/download-artifact@v3
        with:
          name: production-file
          path: current-production
        continue-on-error: true

      - name: Check if artifact exists
        id: artifact-check
        run: echo "artifact_exists=$(if [ -d 'current-production' ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

      - name: Upload previous production artifact
        if: env.artifact_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: previous-production-file
          path: current-production

  # Build Job
  build:
    needs: save-previous-production-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          cd vite-project
          npm install

      - name: Run Tests
        run: |
          cd vite-project
          npm test

      - name: Build Project
        run: |
          cd vite-project
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-file
          path: vite-project/dist

  # Deploy Job
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy if the branch is main
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.POC_LOTTO }}
          publish_dir: vite-project/dist

  # Rollback Job
  rollback:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'rollback'
    steps:
      - name: Download previous artifact
        id: download_previous
        uses: actions/download-artifact@v3
        with:
          name: previous-production-file
        continue-on-error: true

      - name: Check if previous artifact exists
        run: if [ ! -d 'vite-project/dist' ]; then echo "No previous artifact found. Exiting."; exit 1; fi

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.POC_LOTTO }}
          publish_dir: vite-project/dist
