name: CI/CD for React

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify action: deploy or rollback'
        required: true
        default: 'deploy'

      branch:
        description: 'Branch to roll back'
        required: true
        default: 'main'
      commit_hash:
        description: 'Commit hash to roll back to'
        required: true

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          cd vite-project
          npm install
          
      - name: Run Tests
        run: |
          cd vite-project
          npm test

      - name: Build Project
        run: |
          cd vite-project
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: vite-project/dist

          

  # Rollback Job
  rollback:
    if: github.event.inputs.action == 'rollback'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Reset branch to commit hash
        run: |
          BRANCH=${{ github.event.inputs.branch }}
          COMMIT_HASH=${{ github.event.inputs.commit_hash }}
          git checkout main
          git reset --hard $COMMIT_HASH
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.POC_LOTTO }}
