name: CI/CD for React

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify action: deploy or rollback'
        required: true
        default: 'deploy'

jobs:
  # Save Previous Production File Job
  save-previous-production-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Download current production artifact to 'current-production' directory
      - name: Download current production artifact
        if: github.ref == 'refs/heads/main'
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: production-file
          path: current-production

      # Check if the 'current-production' directory exists
      - name: Check if artifact exists
        id: check-artifact
        run: |
          if [ -d "current-production" ]; then
            echo "artifact_exists=true" >> $GITHUB_ENV
          else
            echo "artifact_exists=false" >> $GITHUB_ENV
          fi
      
      # Upload contents of 'current-production' as 'previous-production-file' if the artifact exists
      - name: Upload previous production artifact
        if: env.artifact_exists == 'true' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: previous-production-file
          path: current-production

  # Build Job
  build:
    needs: save-previous-production-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          cd vite-project
          npm install
          
      - name: Run Tests
        run: |
          cd vite-project
          npm test

      - name: Build Project
        run: |
          cd vite-project
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: vite-project/dist

          
  # Deploy Job
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy if the branch is main
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.POC_LOTTO }}
          publish_dir: vite-project/dist

  # Rollback Job
  rollback:
    if: github.event.inputs.action == 'rollback'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download previous artifact
        uses: actions/download-artifact@v4
        with:
          name: previous-production-file
          path: previous-production
        continue-on-error: false

      - name: List artifact contents
        run: ls -l previous-production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.POC_LOTTO }}
          publish_dir: previous-production
