name: CI/CD for React

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify action: deploy or rollback'
        required: true
        default: 'deploy'

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          cd vite-project
          npm install
          
      - name: Run Tests
        run: |
          cd vite-project
          npm test

      - name: Build Project
        run: |
          cd vite-project
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: vite-project/dist
          retention-days: 7


      - name: Download current production artifact
        if: github.ref == 'refs/heads/main'
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: production-file


  # Rollback Job
  rollback:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'rollback'
    steps:
      - name: Download previous artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.POC_LOTTO }}
