name: Rollback

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify action: rollback'
        required: true
        default: 'rollback'
      commit_id:
        description: 'Commit ID SHA to rollback to'
        required: true
        

jobs:
  rollback:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'rollback'
 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to CodeDeploy
        id: deploy
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=deploy-package-${{ github.event.inputs.commit_id }}.zip,bundleType=zip \
            --query "deploymentId" --output text)
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV